const employees = [
  {id:1, firstName:"Alexis", lastName:"DESPLATS", role:"CEO", company:"Cube Golem France / Khadou France", managerId:null, email:"a.desplats@saga-alliance.com", phone:"+33 6 47 32 13 75"},
  {id:2, firstName:"Fabien", lastName:"SOUTIF", role:"Logistic Director", company:"Cube Golem France / Khadou France", managerId:1, email:"f.soutif@khadou.fr", phone:"+33 1 30 47 47 29"},
  {id:3, firstName:"Adrien", lastName:"REAUX", role:"Sales Director", company:"Cube Golem France / Khadou France", managerId:1, email:"a.reaux@cubegolem.fr", phone:"+33 1 30 47 47 28"},
  {id:4, firstName:"Solène", lastName:"GUEBLE", role:"Administrative Manager", company:"Khadou France", managerId:3, email:"s.gueble@khadou.fr", phone:"+33 1 30 47 47 27"},
  {id:5, firstName:"Roberto", lastName:"LLORENS", role:"Customer Support", company:"Cube Golem France", managerId:3, email:"r.llorens@cubegolem.fr", phone:"+33 1 30 47 21 60"},
  {id:6, firstName:"Doaa", lastName:"KADDOURI", role:"Sales & Purchase Assistant", company:"Khadou France", managerId:3, email:"d.kaddouri@khadou.fr", phone:"+33 1 30 47 21 61"},
  {id:7, firstName:"Noémie", lastName:"CUOMO", role:"Supply Chain & Logistic Assistant", company:"Cube Golem France / Khadou France", managerId:2, email:"n.cuomo@khadou.fr", phone:"+33 1 30 47 21 62"},
  {id:8, firstName:"Matthieu", lastName:"BONNINGUE", role:"Forklift Operator", company:"Cube Golem France / Khadou France", managerId:2, email:"m.bonningue@cubegolem.fr", phone:"+33 1 30 47 47 31"},
  {id:9, firstName:"Thibaud", lastName:"HERPIN", role:"Stock Manager", company:"Cube Golem France / Khadou France", managerId:2, email:"logistique@cubegolem.fr", phone:"+33 1 30 47 21 60"},
  {id:10, firstName:"Alexander", lastName:"DUBYNSKI", role:"Managing Partner", company:"Cube Golem Group", managerId:null, email:"a.dubynski@saga_alliance.com", phone:"+49 177 300 0000"},
  {id:11, firstName:"Gregory", lastName:"BENASSAR", role:"CEO", company:"Heathside", managerId:null, email:"greg@heathside.biz", phone:"+33 6 32 12 54 60"},
  {id:12, firstName:"Alistair", lastName:"RINGLAND", role:"Logistic Director", company:"Heathside", managerId:11, email:"alistair@heathside.biz", phone:"+44 777 190 00240"},
  {id:13, firstName:"Nic", lastName:"ALDRIDGE", role:"Head of Khadou Global", company:"Heathside", managerId:11, email:"nic@khadou.com", phone:"+44 794 782 5133"},
  {id:14, firstName:"Sam", lastName:"MYERS", role:"Head of Product Management", company:"Heathside", managerId:11, email:"sam@heathside.biz", phone:"+44 753 491 4120"},
  {id:15, firstName:"Reinhard", lastName:"SIGEL", role:"CO CEO", company:"Cube Golem Germany", managerId:10, email:"reinhard.sigel@funtainment.de", phone:"0049 89 614219 32"},
  {id:16, firstName:"Jurgen", lastName:"BROY", role:"CO-CEO", company:"Cube Golem Germany", managerId:10, email:"", phone:""},
  {id:17, firstName:"Peter", lastName:"MÜLLER", role:"Head of Logistics", company:"Cube Golem Germany", managerId:15, email:"peter.mueller@funtainment.de", phone:"0049 89 614219 22"},
  {id:18, firstName:"", lastName:"", role:"Head of Sales", company:"Cube Golem Germany", managerId:15, email:"", phone:""},
  {id:19, firstName:"Daniel", lastName:"KRÜCKEL", role:"Head of Purchase", company:"Cube Golem Germany", managerId:15, email:"daniel.krueckel@funtainment.de", phone:"0049 89 614219 26"},
  {id:20, firstName:"Andrea", lastName:"KLÜGER", role:"Head of Bookkeeping", company:"Cube Golem Germany", managerId:15, email:"andrea.klueger@funtainment.de", phone:"0049 89 614219 24"},
  {id:21, firstName:"Arnaud", lastName:"FRANGEUL", role:"CO-CEO", company:"Hubtoys", managerId:null, email:"a.frangeul@hubtoys.fr", phone:"+33 6 75 25 32 60"},
  {id:22, firstName:"José", lastName:"MARTINEZ", role:"CO-CEO", company:"Hubtoys", managerId:null, email:"j.martinez@hubtoys.fr", phone:""},
  {id:23, firstName:"Thomas", lastName:"TURBE", role:"", company:"Hubtoys", managerId:21, email:"t.turbe@hubtoys.fr", phone:""},
  {id:24, firstName:"Eve", lastName:"SOULLIER", role:"Administrative Assistant", company:"Hubtoys", managerId:21, email:"support@hubtoys.fr", phone:"+33 6 89 93 33 69"},
  {id:25, firstName:"Nik", lastName:"KROSELJ", role:"CEO", company:"Cube Golem Slovenia", managerId:null, email:"n.kroselj@cubegolem.si", phone:"+38 6 51 24 04 40"},
  {id:26, firstName:"Adja", lastName:"SOSKO", role:"Warehouse Manager", company:"Cube Golem Slovenia", managerId:25, email:"a.sosko@cubegolem.si", phone:"+38 6 40 75 25 17"}
];
